build:
    environment:
        php: '7.2'

    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
        tests: true
    tests:
        before:
            - bash .github/install-wp-tests.sh wordpress_test root '' localhost latest
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'

filter:
    excluded_paths:
        - 'tests/*'
        - '*.min.js'
        - 'gulpfile.js'
    dependency_paths:
        - wordpress/
